# Generated by Django 5.2.13 on 2026-04-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('db_alias', models.CharField(max_length=50)),
                ('db_dsn', models.CharField(max_length=100)),
                ('db_name', models.CharField(max_length=100)),
                ('db_server', models.CharField(max_length=100)),
                ('db_host', models.CharField(max_length=200)),
                ('logo', models.CharField(blank=True, max_length=200)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
