# Generated by Django 5.2.13 on 2026-04-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='db_engine',
            field=models.CharField(choices=[('django_informixdb', 'Informix'), ('django.db.backends.postgresql', 'PostgreSQL'), ('django.db.backends.mysql', 'MySQL'), ('django.db.backends.oracle', 'Oracle'), ('mssql', 'SQL Server')], default='django_informixdb', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='db_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
