# Generated by Django 5.2.13 on 2026-04-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cgrta001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_compania', models.CharField(blank=True, max_length=60, null=True)),
                ('ct_cuenta', models.CharField(blank=True, max_length=60, null=True)),
                ('ct_descripcion', models.CharField(blank=True, max_length=60, null=True)),
                ('ct_estado', models.CharField(blank=True, max_length=60, null=True)),
                ('ct_nivel', models.CharField(blank=True, max_length=60, null=True)),
                ('ct_signo', models.CharField(blank=True, max_length=60, null=True)),
                ('ct_tipo', models.CharField(blank=True, max_length=60, null=True)),
                ('ct_dolar', models.CharField(blank=True, max_length=60, null=True)),
                ('ct_db_ano_ant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_cr_ano_ant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_db_mes01', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_db_mes02', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_db_mes03', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_db_mes04', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_db_mes05', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_db_mes06', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_db_mes07', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_db_mes08', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_db_mes09', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_db_mes10', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_db_mes11', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_db_mes12', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_cr_mes01', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_cr_mes02', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_cr_mes03', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_cr_mes04', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_cr_mes05', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_cr_mes06', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_cr_mes07', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_cr_mes08', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_cr_mes09', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_cr_mes10', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_cr_mes11', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_cr_mes12', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_db_mes01s', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_db_mes02s', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_db_mes03s', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_db_mes04s', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_cr_mes01s', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_cr_mes02s', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_cr_mes03s', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_cr_mes04s', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ct_usuario', models.CharField(blank=True, max_length=60, null=True)),
                ('ct_fhalta', models.DateTimeField()),
            ],
            options={
                'db_table': 'cgrta001',
                'managed': False,
            },
        ),
    ]
